name: Deploy dynomenu.com Frontend
on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DO Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.KEY}}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            echo "1 -- Remove existing directory"
            rm -rf frontend-main
            echo "2 -- Cloning Repository"
            git clone git@github.com:dyno-verse/frontend-main.git
            cd frontend-main
            echo "3 -- Installing dependencies"
            npm install
            echo "4 -- Building application"
            npm run generate
            echo "============================================="
            echo "✅✅✅✅✅ App build complete"